### ISSUE TITLE
customizing massstorage

### ISSUE THREAD

**Issue by ahmedfamhy3** [Netdex/android-usb-script#13]
how i can customize the masstorage there isn't any wiki or documentation

**Comment by Netdex** [comment]
See [LuaUsbLibrary.java](https://github.com/Netdex/android-usb-script/blob/master/app/src/main/java/org/netdex/androidusbscript/task/LuaUsbLibrary.java#L171) for the list of options that can be passed to the mass storage gadget.
```java
String file = config.get("file").optjstring("/data/local/tmp/mass_storage-lun0.img");
boolean ro = config.get("ro").optboolean(false);
long size = config.get("size").optlong(256);
```

Here's an example with all the default options explicitly specified:
```lua
_ = luausb.create({ 
    id = 0, 
    type = "storage",
    file = "/data/local/tmp/mass_storage-lun0.img",  -- location of backing file
    ro = false,                                      -- read-only
    size = 256                                       -- size in MiB
})
```
