### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [Netdex/android-usb-script#15]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by Netdex** [comment]
The APK artifacts provided in this repository are for development purposes and are not intended to be installed on a device for daily use.

Relevant meme:
<details>
![image](https://github.com/Netdex/android-usb-script/assets/2091886/7a6dffe1-4b83-4b9c-a2e9-12a0fd98e520)
</details>

**Comment by IzzySoft** [comment]
Then would you consider to make APKs for "daily use" available here? Asking because your app is [in my repo](https://apt.izzysoft.de/packages/org.netdex.hidfuzzer/) since 11/2020.

**Comment by Netdex** [comment]
Ah, didn't realize the APKs were being published somewhere. I published a new release with signed artifacts.

**Comment by IzzySoft** [comment]
Yes, it's a repo for FOSS apps. To make them easier to find and keep them updated on-device. You can choose your favorite [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) as well as your favorite [repositories](https://android.izzysoft.de/articles/named/list-of-fdroid-repos). Mine just happens to be the second largest…

Thanks for doing this! Please give me a ping here when they're available here, as I need to do some adjustments on my end then, too (like, pinning the hash of the new certificate as it would otherwise be rejected; and including a hint that those using an older version need to uninstall/reinstall).

PS: Ah wait, you wrote "published", so I'll check right now!

**Comment by IzzySoft** [comment]
Ah, package renamed as well – yeah, when better than now, as to update one needs to uninstall/reinstall anyway :wink: 

![image](https://github.com/Netdex/android-usb-script/assets/6781438/0daede65-2191-4dfc-9c3d-c5318ea80509)

If you want to have some icon/screenshots included, just let me have them. I can also offer you a PR with the metadata I've set up on my end to integrate them here with your repo, so you can adjust as you see fit and modifications would be fetched with each update. I'm using Fastlane structures for that (which are the quasi-standard in the Android world), and you can use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance. Just let me know.

![image](https://github.com/Netdex/android-usb-script/assets/6781438/9d658fa7-aa37-4900-8706-902de36d65ac)

looks good as well. If you want to get rid of that blob (`DEPENDENCY_INFO_BLOCK`):

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Thanks a lot once more – and feel free to close this issue unless you want to keep it open for "the BLOB" :wink:

**Comment by Netdex** [comment]
> Yes, it's a repo for FOSS apps

Very cool.

> Ah, package renamed as well

Yeah, I must have done that at some point... thanks for making the necessary adjustments.

> I can also offer you a PR with the metadata I've set up on my end to integrate them here with your repo

That would be great 🙂 

> If you want to get rid of that blob (DEPENDENCY_INFO_BLOCK)

Re-uploaded the latest release artifact with "the BLOB" gone.

**Comment by IzzySoft** [comment]
> That would be great 🙂

There you go :smiley: Should questions arise, feel free to reach out.

> Re-uploaded the latest release artifact with "the BLOB" gone.

Thanks! Confirmed and replaced here as well.
