### ISSUE TITLE
send key delete

### ISSUE THREAD

**Issue by chungdtph03756** [Netdex/android-usb-script#3]
I want to send command of delete button to pc
please help me

**Comment by Netdex** [comment]
The Lua command `press_keys(kb.DELETE)` would send a delete key.

A full list of input keys is available in [Input.java](https://github.com/Netdex/android-hid-script/blob/master/app/src/main/java/cf/netdex/hidfuzzer/hid/Input.java).
A full list of Lua commands is available in [LuaHIDBinding.java](https://github.com/Netdex/android-hid-script/blob/master/app/src/main/java/cf/netdex/hidfuzzer/lua/LuaHIDBinding.java).
Some example self-documenting scripts are available in [assets/scripts](https://github.com/Netdex/android-hid-script/tree/master/app/src/main/assets/scripts).
